cluster:
  cloud: amazon
  location: us-east-2
  name: lpuskasrl7x
  postHooks:
    InstallAnchoreImageValidator:
      enable: true
    InstallLogging:
      bucketName: sancinak
      secretId: 16e5344c9cba3b804e54d4053ab611a39cc4fba123c715b17dfbfc292c497508
    InstallMonitoring:
      enabled: true
  properties:
    pke:
      cri:
        runtime: containerd
      kubernetes:
        rbac:
          enabled: true
        version: 1.15.3
      nodepools:
      - autoscaling: false
        name: master
        provider: amazon
        providerConfig:
          autoScalingGroup:
            instanceType: c5.large
            launchConfigurationName: master
            name: master
            size:
              desired: 1
              max: 1
              min: 1
            spotPrice: ""
            zones:
            - us-east-2a
        roles:
        - master
      - autoscaling: true
        name: pool1
        provider: amazon
        providerConfig:
          autoScalingGroup:
            instanceType: t2.medium
            launchConfigurationName: pool1
            name: pool1
            size:
              desired: 1
              max: 2
              min: 1
            spotPrice: "0.0464"
            zones:
            - us-east-2a
        roles:
        - worker
      - autoscaling: true
        name: pool2
        provider: amazon
        providerConfig:
          autoScalingGroup:
            instanceType: m4.large
            launchConfigurationName: pool2
            name: pool2
            size:
              desired: 1
              max: 2
              min: 1
            spotPrice: "0.1"
            zones:
            - us-east-2a
        roles:
        - worker
      - autoscaling: true
        name: pool3
        provider: amazon
        providerConfig:
          autoScalingGroup:
            instanceType: c5.large
            launchConfigurationName: pool3
            name: pool3
            size:
              desired: 1
              max: 2
              min: 1
            spotPrice: "0.085"
            zones:
            - us-east-2a
        roles:
        - worker
  secretId: 16e5344c9cba3b804e54d4053ab611a39cc4fba123c715b17dfbfc292c497508
pipeline:
  install_history_server_bucket_secrets:
    action: InstallSecret
    clusterSecret:
      convertToPreferredFormat: true
      merge: true
      name: '{{ .CICD_REPO_NAME }}-hs-bucket'
      namespace: default
      sourceSecretName: puski-aws
      spec: []
    image: banzaicloud/ci-pipeline-client:0.11
  install_history_server_auth_secrets:
    action: InstallSecret
    clusterSecret:
      merge: true
      name: '{{ .CICD_REPO_NAME }}-hs-auth'
      namespace: default
      sourceSecretName: historyserverpass
      spec:
      - name: htpasswd
        source: htpasswd
    image: banzaicloud/ci-pipeline-client:0.11
  package_application:
    image: lachlanevenson/k8s-helm:latest
    commands:
    - helm init -c
    - helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
    - helm package -u ./.banzaicloud/charts/spotguide-spark
  deploy_application:
    action: EnsureDeployment
    deployment:
      name: ./spotguide-spark-1.0.0.tgz
      namespace: default
      releaseName: '{{ .CICD_REPO_NAME }}'
      values:
        banzaicloud:
          bucket:
            location: eu-central-1
            namespace: null
            storageAccountName: null
          interpreter: Scala
          secret:
            historyServer:
              name: historyserverpass
          security:
            enabled: true
          spark:
            executor:
              num: "2"
            image:
              tag: v2.4.3.211
            version: 2.4.3
        historyServer:
          enabled: true
        spark:
          monitoring:
            enabled: true
            jmxCollector: |
              lowercaseOutputName: false
              lowercaseOutputLabelNames: false
              whitelistObjectNames: ["*:*"]
            metricsProperties: |
              # Enable Prometheus for all instances by class name
              *.sink.prometheus.class=com.banzaicloud.spark.metrics.sink.PrometheusSink
              # Prometheus pushgateway address
              *.sink.prometheus.pushgateway-address=prometheus-pushgateway.pipeline-system:9091
              *.sink.prometheus.pushgateway-enable-timestamp=true
              *.sink.prometheus.enable-dropwizard-collector=true
              *.sink.prometheus.enable-jmx-collector=false
          spark-hs:
            image:
              tag: v2.4.3.211
            ingress:
              annotations:
                ingress.kubernetes.io/ssl-redirect: "true"
                kubernetes.io/ingress.class: traefik
                traefik.frontend.rule.type: PathPrefixStrip
                traefik.ingress.kubernetes.io/auth-secret: '{{ .CICD_REPO_NAME }}-hs-auth'
                traefik.ingress.kubernetes.io/auth-type: basic
              enabled: true
              hosts:
              - shs-{{ (printf "%s-%s" .CICD_REPO_NAME .CLUSTER_NAME) | sha1sum | trunc 10}}.{{.ORG_NAME | lower}}.{{.DOMAIN_NAME}}
            sparkEventLogStorage:
              aliOssRegion: eu-central-1
              azureStorageAccountName: null
              cloudProvider: amazon
              logDirectory: puski-spark-spotguide
              oracleNamespace: null
              oracleRegion: eu-central-1
              pipelineSecretName: puski-aws
              secretName: '{{ .CICD_REPO_NAME }}-hs-bucket'
    image: banzaicloud/ci-pipeline-client:0.11
